### ISSUE TITLE
Custom Font title

### ISSUE THREAD

**Issue by ihusnainalii** [LinusGeffarth/LGSegmentedControl#1]
Do we use custom font size for LGSegment?
like in public class LGSegment we have titleLabel but it is not updating can you please help me out? i have update the public initializer as 

    public init(title: String, badgeCount: Int? = nil) {
        self.title = title
        self.titleLabel.font = UIFont.systemFont(ofSize: 12)
        self.badgeCount = badgeCount
        updateAppearance(with: options, animated: false)
        setupConstraints()
    }

Waiting for response.
Thanks in advance.

**Comment by LinusGeffarth** [comment]
Hey, you don't need to modify the initializer. I suggest reverting that section.

Instead, you can use the `LGOptions` and set the `.font` property.

Looks like I forgot to add that in the docs; added it now.
